### PR TITLE
Feature darktheme

### PR DESCRIPTION
**Pull request by loial**
Adds dark theme.

In my use case, I use the app in low light settings and light turned all the way down on the phone, so a dark theme makes more sense to me. Also, only makes sense of applied at app startup, so I introduced persisting setting for the checkbox. Could probably add the other settings too, so the app remembers what sound where used last time.

### CODE REVIEW

**Comment by brarcher** [comment]
I like it! 

screen shot 2017-12-10 at 9 41 36 am

The only suggest I have is to change "Use dark theme" to "Use Dark Theme" to match the case used in the other settings. I'll see if I can make that change on the branch.

**Comment by brarcher** [comment]
Thanks for the dark theme feature! Glad the app is useful.

**Comment by loial** [comment]
Cool! I noticed the casing were wrong right after I made the pull request, but this being my first PR (or rather, first two :) ) I was unsure how to properly move forward after the PR was created...

I like the app, and its ease of use.  Tried a few times for its intended purpose but didn't have too much effect on my kids. But I've used it a few times for myself, and to add a little white noise, when I don't bring my noise cancelling headset.

Also great code to play around with, learning Android, and git(hub) workflow.

**Comment by brarcher** [comment]
> Tried a few times for its intended purpose but didn't have too much effect on my kids.

I hear you. I created it for my fist son, hoping it would be helpful. I was never able to find success with it, but the daycare he goes to uses a commercial product (that does the same stuff) and swears by it. Others have mentioned that the app is helpful for their children. So, maybe hit is hit or miss.

If you have any ideas for sounds that you would like added, let me know. If they can be found online with an acceptable license they are easy enough to add.

**Pull request merged**
