### PR TITLE
Settings UI activity

### PR DESCRIPTION
**Pull request by pserwylo**
As per the itesm in [the wishlist](https://github.com/brarcher/baby-sleep-sounds/issues/70#issuecomment-364664744) of #70, this PR does the following:

* [x] Persist low pass filter configurations between app launches
* [x] Move filter settings to a settings menu
* [ ] Move the timer setting to its final location.
* [ ] List sounds in a text list (or something else) on the screen, in the layout similar to its final layout
* [ ] Change the sound text to images

It does this by:
* Moving relevant preferences to a new `SettingsActivity` (low pass enabled, low pass filter value, theme - previously "Dark Mode Enabled").
* Therefore settings regarding low pass filter configurations are now persisted to the default shared preferences used by the preference fragment.
* Migrates to AndroidX to make use of the new UI components available to help with the preferences fragment (and later refactoring the main UI).

image 
image 
image

Note that the sequence of commits works through items in the wishlist in some sort of order, so please feel free to just pick whatever commits you desire. Each subsequent commit generally depends on the earlier ones though, hence them being in the same PR. 

In order to make this easier to implement, more maintainable into the future, and also to feel as much like a modern android app as possible, this involved:

* Migrating from support lib to AndroidX, which in turn required
* Bumping the target SDK to 29 (latest), and also
* Bumping the build tools, which in turn required
* Replacing findbugs with spotbugs as the findbugs plugin was deprecated then removed in Gradle 5 (this is now using Gradle 6).

Would be good to get some feedback on whether spotbugs works as expected.

### CODE REVIEW

**Comment by pserwylo** [comment]
Please note, if this is too much to merge at once, perhaps you'd like to look at just merging the AndroidX stuff first: https://github.com/pserwylo/baby-sleep-sounds/tree/androidx or the persisting of the filter settings (#83).

**Comment by pserwylo** [comment]
Also not sure what "1 expected check" is. If any of the checks fail, just let me know and I'll try to get it up to scratch.

**Comment by pserwylo** [comment]
51cea36 changes the theme from AppCompat to Material, simplifying the theming quite a bit, but it does change the styles a little. I've left them as the default for now, but happy to tweak if you have any feedback or wish for a like-for-like comparison with the existing version:

image image

image 
image

**Comment by brarcher** [comment]
Catching up to your changes now. I'd not heard of spotbugs before, pretty cool. Also, the changes you propose sound good. I appreciate it.

I've not been that active in this project recently, as some other stuff has been taking my time. The automated build and test setup no longer works (Travis-CI). Now that GitHub Actions is available, the project should move to that instead. Let me see if I can set that up, so this change will build and test before it is submitted.

**Comment by brarcher** [comment]
So, getting Actions to work was easy, but the build does not pass because the project is currently using some deprecated stuff. I think that your changes should resolve that.

Would you mind adding a commit similar to https://github.com/brarcher/baby-sleep-sounds/pull/85 and see if the build can pass with your changes?

**Comment by pserwylo** [comment]
Thanks for the feedback. I've cherry-picked the github actions file, and tweaked it a little (add `--stacktrace` to the build in case of failure, change findbugs to spotbugs for this branch), and fixed one lint error that caused a failure. 

I'm dubious whether spotbugs is actually running correctly due to missing Android classes on the classpath (https://github.com/brarcher/baby-sleep-sounds/pull/84/checks?check_run_id=1311141182).

**Comment by brarcher** [comment]
> I'm dubious whether spotbugs is actually running correctly due to missing Android classes on the classpath

I've seen the same thing from FindBugs. However, FindBugs still found and reported issues. Probably it's working just fine.

Thanks for adding in the Github Actions file!

Looking over everything, and trying it out myself, looks good. Thanks for the contribution!

**Pull request merged**
